[pytest]
# Suppress deprecation warnings coming from quantities / elephant internals
filterwarnings =
    ignore:.*The 'copy' argument in Quantity is deprecated.*:DeprecationWarning
    ignore:.*'complexity_pdf' is deprecated in favor of the Complexity class which has a 'pdf' method
    ignore:.*No sampling rate specified. Note that using the complexity epoch to get precise 
    ignore:.*the matrix subclass is not the recommended way to represent matrices or deal with linear algebra